site_name: Random Musings - Rambling of a curious engineer & data scientist!

site_url: https://suneeta-mall.github.io/
site_dir: site

use_directory_urls: true
strict: true

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  # logo: resources/logo.svg
  # favicon: resources/logo_large_azure.svg
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.breadcrumbs
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - git-revision-date-localized:
        type: date
        enable_creation_date: true

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

  language: en

  font:
    text: Roboto
    code: Roboto Mono

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suneeta-mall-a6a0507/
    - icon: fontawesome/brands/github
      link: https://github.com/suneeta-mall
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/suneetamall/
    - icon: fontawesome/brands/medium
      link: https://www.medium.com/@suneetamall
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com.au/citations?hl=en&user=WD712CUAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Suneeta_Mall3
    - icon: fontawesome/solid/rss
      link: https://suneeta-mall.github.io/feed_rss_created.xml
    - icon: fontawesome/solid/envelope
      link: mailto:suneetamall@gmail.com

plugins:
  - blog:
      authors: true
  - social
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_file: tags.md
      tags_allowed: true
      tags_extra_files:
        - docs/blog/posts/*.md
        - docs/projects/*.md
        - docs/talks/*.md
        - docs/poems/*.md
  - privacy
  - rss:
      site_url: https://suneeta-mall.github.io/
      image_handling: true
      image_handling_absolute: true
  - literate-nav:
      nav_file: SUMMARY.md
  - bibtex:
      bib_file: "docs/references/refs.bib"
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - recent_posts

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "-"
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  homepage: https://suneeta-mall.github.io/
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suneeta-mall-a6a0507/
    - icon: fontawesome/brands/github
      link: https://github.com/suneeta-mall
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/suneetamall/
    - icon: fontawesome/brands/medium
      link: https://www.medium.com/@suneetamall
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com.au/citations?hl=en&user=WD712CUAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Suneeta_Mall3
    - icon: fontawesome/solid/rss
      link: https://suneeta-mall.github.io/feed_rss_created.xml
    - icon: fontawesome/solid/envelope
      link: mailto:suneetamall@gmail.com
  copyright: Copyright &copy; 2016 - 2024 Suneeta Mall
  generator: false
  version:
    provider: mike

nav:
  - Home: README.md
  - Projects:
    - Deep Learning at Scale: projects/oreilly_deep_learning_at_scale.md
    - Curious Cassie - The Children's Books: projects/curious_cassie.md
    - Label Noise with Clean Lab: projects/feature_analysis.md
    - Feature Analysis: projects/feature_analysis.md
    - Oreilly Katacode Series: projects/oreilly-interactive-katacode-series-for-reproducible-ml.md
    - Reproducible-ML: projects/reproducible-ml.md
    - KCD: projects/KCD.md
  - Blog:
    - blog/index.md
  - Tags: tags.md
  - Talks:
    - Knowledge Graph Conference 2022: talks/KGC_NY_2022.md
    - KubeCon NA 2021: talks/KubeCon_NA_2021.md
    - Kafka Summit APAC 2021: talks/Kafka_Summit_APAC_2021.md
    - AWS Community Day 2020: talks/AWS_ANZ_Commuity_day_2020.md
    - AWS She Builds on AWS 2020: talks/She_Builds_on_AWS_2020.md
    - KubeCon US 2019: talks/KubeCon_US_2019.md
    - Kubernetes Sydney 2019: talks/KubernetesSydneyForum_AU_2019.md
    - YOW Data 2019: talks/YOW_Data_Syd_2019.md
    - KubeCon EU 2018: talks/KubeCon-Europe-2018.md
    - SPIE 2019: talks/SPIE-2019.md
    - SPIE 2018: talks/SPIE-2018.md
    - SPIE 2015: talks/SPIE-2015.md
  - Poems:
    - Singularity: poems/singularity.md
    - Life of AI Engineers: poems/life-of-ai-engineer.md
    - My little Butterfly: poems/my-little-butterfly.md
    - Breaking Thy Bias: poems/breaking-thy-bias.md
    - Daminis: poems/daminis.md
    - One Bright Dawn: poems/one-bright-dawn.md
    - Aint no Dr. Seuss: poems/aint-no-dr-seuss.md
  - About Me: about.md