site_name: Suneeta Mall | Engineering and Data Science
site_description: Engineering and Data Science insights, tutorials, and projects

site_url: https://suneeta-mall.github.io/
site_dir: site

use_directory_urls: true
strict: false

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  logo: resources/site/logo.svg
  favicon: resources/site/favicon.svg
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.follow
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.breadcrumbs
    - navigation.expand
    - toc.integrate
  sitemap:
    filename: sitemap.xml
    changefreq: monthly
    priority: 0.5

  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: en

  font:
    text: Roboto
    code: Roboto Mono

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suneeta-mall-a6a0507/
    - icon: fontawesome/brands/github
      link: https://github.com/suneeta-mall
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/suneetamall/
    - icon: fontawesome/brands/medium
      link: https://www.medium.com/@suneetamall
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com.au/citations?hl=en&user=WD712CUAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Suneeta_Mall3
    - icon: fontawesome/solid/rss
      link: https://suneeta-mall.github.io/feed_rss_created.xml
    - icon: fontawesome/solid/envelope
      link: mailto:suneetamall@gmail.com

plugins:
  - blog:
      authors: true
      blog_dir: blog
      post_dir: blog/posts
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_readtime: true
      post_readtime_words_per_minute: 200
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags
  - rss:
      enabled: true
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      comments_path: "#__comments"
      pretty_print: true
      length: 20
      feeds_filenames:
        rss_created: feed_rss_created.xml
        rss_updated: feed_rss_updated.xml
        json_created: feed_json_created.json
        json_updated: feed_json_updated.json
      abstract_chars_count: 160
      use_git: false
  - bibtex:
      bib_file: "docs/references/refs.bib"
      bib_by_default: true
  - literate-nav:
      nav_file: SUMMARY.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "-"
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  homepage: https://suneeta-mall.github.io/
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suneeta-mall-a6a0507/
    - icon: fontawesome/brands/github
      link: https://github.com/suneeta-mall
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/suneetamall/
    - icon: fontawesome/brands/medium
      link: https://www.medium.com/@suneetamall
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com.au/citations?hl=en&user=WD712CUAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Suneeta_Mall3
    - icon: fontawesome/solid/rss
      link: https://suneeta-mall.github.io/feed_rss_created.xml
    - icon: fontawesome/solid/envelope
      link: mailto:suneetamall@gmail.com
  copyright: Copyright &copy; 2016 - 2024 Suneeta Mall
  generator: false
  version:
    provider: mike
  javascript:
    - javascripts/extra.js
  css:
    - stylesheets/extra.css

nav:
  - Home: README.md
  - About: about.md
  - Projects:
      - projects/index.md
      - Deep Learning at Scale: projects/oreilly_deep_learning_at_scale.md
      - Curious Cassie Children's Books: projects/curious_cassie.md
      - Label Noise with CleanLab: projects/label_noise_with_cleanlabs.md
      - Feature Analysis: projects/feature_analysis.md
      - O'Reilly Interactive Series: projects/oreilly-interactive-katacode-series-for-reproducible-ml.md
      - Reproducible ML: projects/reproducible-ml.md
      - KCD: projects/KCD.md
      # - Gatling on ECS: projects/gatling-on-ecs.md
      # - Go Report Card Lite: projects/goreportcardlite.md
  - Blog:
      - blog/index.md
  - Talks:
      - talks/index.md
      - Knowledge Graph Conference 2022: talks/KGC_NY_2022.md
      - KubeCon NA 2021: talks/KubeCon_NA_2021.md
      - Kafka Summit APAC 2021: talks/Kafka_Summit_APAC_2021.md
      - AWS Community Day 2020: talks/AWS_ANZ_Commuity_day_2020.md
      - AWS She Builds 2020: talks/She_Builds_on_AWS_2020.md
      - KubeCon US 2019: talks/KubeCon_US_2019.md
      - Kubernetes Sydney 2019: talks/KubernetesSydneyForum_AU_2019.md
      - YOW Data 2019: talks/YOW_Data_Syd_2019.md
      - KubeCon EU 2018: talks/KubeCon-Europe-2018.md
      - SPIE 2019: talks/SPIE-2019.md
      - SPIE 2018: talks/SPIE-2018.md
      - SPIE 2015: talks/SPIE-2015.md
      - Strata Data & AI US 2020: talks/Strata_Data_AI_US_2020.md
  - Creative:
      - Poems:
          - poems/index.md
          - Singularity: poems/singularity.md
          - Life of AI Engineers: poems/life-of-ai-engineer.md
          - My Little Butterfly: poems/my-little-butterfly.md
          - Breaking Thy Bias: poems/breaking-thy-bias.md
          - Daminis: poems/daminis.md
          - One Bright Dawn: poems/one-bright-dawn.md
          - Ain't No Dr. Seuss: poems/aint-no-dr-seuss.md
      - Children's Books:
          - Curious Cassie Series: projects/curious_cassie.md
          - Beach Ride Quest Launch: blog/posts/2023-11-15-Curious-Cassie.md
          - ChatGPT vs Me as Author: blog/posts/2024-01-07-ChatGPT_vs_me_kids_book_author.md
  - Tags: tags.md
